import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import ProductCard from "../product-components/Productcard";
import product1 from '../../assets/images/product1.jpg';
import product2 from '../../assets/images/product2.jpg';
import product3 from '../../assets/images/product1.jpg';
import "../product-components/productcard.css";

const Livestock = () => {
  const navigate = useNavigate();


  const [productdetailsList] = useState([
    {
      id: "productdetails-1",
      name: "Alveliv Liver Tonic",
      image: product1,
      description: "Minimum Order Quantity: 5 Liter | Price: 580 INR/Liter | Alveliv Liver Tonic Product Specifications: Variety: Herbal Supplements, Fragrance: Delicate Smell, Application: Fodders, Suitable For: Cattle, Function: Healthcare supplement, Efficacy: Feed Preservatives, Type: Alveliv Liver Tonic, Texture: Fresh, Physical Form: Liquid | Alveliv Liver Tonic Trade Information: Supply Ability: 300 Liter Per Day, Delivery Time: 10 Days",
      price: "$500",
      relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    },
    
    {
      id: "productdetails-2",
      name: "Weight Gain Forte 5 ltr",
      image: product2,
      description: "Price: 940 INR/Liter | Efficacy: Feed Preservatives | Variety: Organic Feed | Texture: Fresh | Fragrance: Delicate Smell | Suitable For: Cattle | Application: Fodders | Dosage: Solution | Type: Weight Gain Forte | Delivery Time: 10 Days | Supply Ability: 300 Per Day",
      price: "$300",
         relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    },
    
    {
      id: "productdetails-3",
      name: "Digeliv Forte",
      image: product3,
      description: "Price: 1750 INR/Liter | Texture: Fresh | Fragrance: Delicate Smell | Efficacy: Feed Preservatives | Variety: Organic Feed | Function: Healthcare supplement | Physical Form: Liquid | Suitable For: Cattle | Application: Fodders | Supply Ability: 300 Per Day | Delivery Time: 10 Days",
      price: "$400",
         relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    },
    
    {
      id: "productdetails-4",
      name: "Digeliv Forte",
      image: product3,
      description: "Price: 520 INR/Liter | Delivery Time: 10 Days | Supply Ability: 300 Per Day | Fragrance: Delicate Smell | Texture: Fresh | Physical Form: Liquid | Type: Digeliv Forte | Application: Other | Suitable For: Other | Dosage: Other",
      price: "520 INR/Liter",
         relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    }
    ,{
      id: "productdetails-5",
      name: "Alveliv Liver Tonic",
      image: product3,
      description: "Price: 650 NZD ($)/Liter | ALVELIV BEST STRONG LIVER TONIC | Improves Hepatic Functions | Enhances Appetite with Better Digestion & Assimilation | Better F.C.R. | Optimum Growth and Production | Improves Health with Hematinic Effect",
      price: "650 NZD ($)/Liter",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    },
    {
      id: "productdetails-6",
      name: "Salt Lick Almin Salt Tm",
      image: product3,
      description: "Price Range: 450.00 - 4500.00 INR/Pack | Minimum Order Quantity: 100 Pack | Texture: Other | Variety: Nutrition Feeds | Physical Form: Powder | Supply Ability: 1 Pack Per Day | Delivery Time: 1 Day | SALT LICK - ALMIN SALT - TM | Trace Mineral Salt Lick Block for Cattle & Goat | Each kg. contains: Iron: 800 mg, Sodium: 320 gm, Magnesium: 11.5 mg, Iodine: 60 mg, Manganese: 1.5 gm, Cobalt: 40 mg, Zinc: 650 mg, Selenium: 21 mg, Copper: 350 mg | Usage: Allow one block for every cattle and for 10 goats one block preferred | Packing: 5 kg & 2 kg Blocks",
      price: "450.00 - 4500.00 INR/Pack",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    },
    
    {
      id: "productdetails-7",
      name: "Salt Lick Alvilick",
      image: product3,
      description: "Price: 450 INR/Pack | Minimum Order Quantity: 100 Pack | Variety: Nutrition Feeds | Texture: Other | Physical Form: Powder | Supply Ability: 1 Pack Per Day | Delivery Time: 1 Day | SALT LICK - ALVILICK | Mineral Salt Lick Block for Sheep & Goat | Each kg. contains: Iron: 800 mg, Sodium: 320 gm, Magnesium: 11.5 mg, Iodine: 60 mg, Manganese: 1.5 gm, Cobalt: 40 mg, Zinc: 650 mg, Selenium: 21 mg | Usage: Allow for 10 goats or Sheep one block preferred | Packing: 5 kg & 2 kg Blocks",
      price: "450 INR/Pack",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    },
    {
      id: "productdetails-8",
      name: "Salt Lick Calcisalt",
      image: product3,
      description: "Price: 450 INR/Pack | Minimum Order Quantity: 100 Pack | Texture: Other | Physical Form: Powder | Variety: Nutrition Feeds | Supply Ability: 1 Pack Per Day | Delivery Time: 1 Day | SALT LICK - CALCISALT | Calcium with Mineral Salt Lick Block for Cattle & Goats | Each kg. contains: Calcium: 3 gm, Phosphorus: 1 gm, Iron: 800 mg, Sodium: 320 gm, Magnesium: 11.5 mg, Iodine: 60 mg, Manganese: 1.5 gm, Cobalt: 40 mg, Zinc: 650 mg, Selenium: 21 mg, Copper: 350 mg | Usage: Allow one block for every cattle and for 10 goats one block preferred | Packing: 5 kg & 2 kg Blocks",
      price: "450 INR/Pack",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    },
    {
      id: "productdetails-9",
      name: "Aniphocal Suspension",
      image: product3,
      description: "Price: 450 INR/Pack | Minimum Order Quantity: 100 Pack | Physical Form: Powder | Texture: Other | Variety: Nutrition Feeds | Supply Ability: 1 Pack Per Day | Delivery Time: 1 Day | ANIPHOCAL SUSPENSION LIQUID | High Concentration Liquid | Dosage: Cattle & Horse - 100 ml, Calves, Sheep - 20 ml, Chicks, Broilers - 20 ml, Layers - 100 ml daily in 10 liters of drinking water | Each 100 ml contains: Calcium: 2000 mg, Phosphorus: 1000 mg, Vitamin D3: 8000 IU, Vitamin B12: 100 mcg | Improves milk yield in cattle, Prevents calcium deficiencies, Helps to develop strong egg shells, Prevents leg weakness.",
      price: "450 INR/Pack",
         relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    },
    
    {
      id: "productdetails-10",
      name: "Liver Tonic",
      image: product3,
      description: "Price: 85 INR/Pack | Minimum Order Quantity: 100 Pack | Variety: Nutrition Feeds | Texture: Other | Physical Form: Powder | Supply Ability: 1 Pack Per Day | Delivery Time: 1 Day",
      price: "85 INR/Pack",
         relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    },
    {
      id: "productdetails-11",
      name: "Aniphocal Gold Suspension",
      image: product3,
      description: "Price: 560 INR/Pack | Minimum Order Quantity: 100 Pack | Physical Form: Powder | Variety: Nutrition Feeds | Texture: Other | Supply Ability: 1 Pack Per Day | Delivery Time: 1 Day",
      price: "560 INR/Pack",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    },
    {
      id: "productdetails-12",
      name: "Tricalvet Bolus",
      image: product3,
      description: "Price: 170 INR/Pack | Minimum Order Quantity: 100 Pack | Variety: Nutrition Feeds | Physical Form: Powder | Texture: Other | Supply Ability: 1 Pack Per Day | Delivery Time: 1 Day",
      price: "170 INR/Pack",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    }
    ,{
      id: "productdetails-13",
      name: "Fertemin 7 Bolus",
      image: product3,
      description: "Price: 450 INR/Pack | Texture: Other | Physical Form: Powder | Variety: Nutrition Feeds | Delivery Time: 1 Day | Supply Ability: 1 Per Day",
      price: "450 INR/Pack",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    }
    ,{
      id: "productdetails-14",
      name: "Anigrow Liquid Animal Feed Supplement",
      image: product3,
      description: "Price: 450 INR/Pack | Variety: Nutrition Feeds | Texture: Other | Physical Form: Powder | Delivery Time: 1 Day | Supply Ability: 1 Per Day",
      price: "450 INR/Pack",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    },
    {
      id: "productdetails-15",
      name: "Anistress Bolus",
      image: product3,
      description: "Price: 450 INR/Pack | Supply Ability: 1 Per Day | Delivery Time: 1 Day | Texture: Other | Physical Form: Powder | Variety: Nutrition Feeds",
      price: "450 INR/Pack",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    },
    {
      id: "productdetails-16",
      name: "Icp Plus Liquid Iron Calcium And Phosphorus Ble",
      image: product3,
      description: "Price: 450 INR/Pack | Minimum Order Quantity: 100 Pack | Variety: Nutrition Feeds | Physical Form: Powder | Texture: Other | Supply Ability: 1 Pack Per Day | Delivery Time: 1 Day",
      price: "450 INR/Pack",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    }
    ,{
      id: "productdetails-17",
      name: "Biostress Bolus",
      image: product3,
      description: "Price: 450 INR/Pack | Supply Ability: 1 Per Day | Delivery Time: 1 Day | Variety: Nutrition Feeds | Texture: Other | Physical Form: Powder",
      price: "450 INR/Pack",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    }
    ,
    {
      id: "productdetails-18",
      name: "Aminocare Powder",
      image: product3,
      description: "Price: 450 INR/Pack | Delivery Time: 1 Day | Supply Ability: 1 Per Day | Physical Form: Powder | Texture: Other | Variety: Nutrition Feeds",
      price: "450 INR/Pack",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    }
    ,{
      id: "productdetails-19",
      name: "Highpro Powder",
      image: product3,
      description: "Price: 450 INR/Pack | Delivery Time: 1 Day | Supply Ability: 1 Per Day | Physical Form: Powder | Texture: Other | Variety: Nutrition Feeds",
      price: "450 INR/Pack",
      relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    }
    ,{
      id: "productdetails-20",
      name: "Aniboost Powder",
      image: product3,
      description: "Price: 450 INR/Pack | Variety: Nutrition Feeds | Physical Form: Powder | Texture: Other | Delivery Time: 1 Day | Supply Ability: 1 Per Day",
      price: "450 INR/Pack",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    }
    ,{
      id: "productdetails-21",
      name: "Livestock Feed Supplement",
      image: product3,
      description: "Price: 450 INR/Pack | Delivery Time: 1 Day | Supply Ability: 1 Per Day | Variety: Nutrition Feeds | Physical Form: Powder | Texture: Other",
      price: "450 INR/Pack",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    }
    ,{
      id: "productdetails-22",
      name: "Sheep Feed Supplements",
      image: product3,
      description: "Price: 450 INR/Pack | Supply Ability: 1 Per Day | Delivery Time: 1 Day | Variety: Nutrition Feeds | Physical Form: Powder | Texture: Other",
      price: "450 INR/Pack",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    }
    ,{
      id: "productdetails-23",
      name: "Cattle Mineral Feed Supplement",
      image: product3,
      description: "Price: 450 INR/Pack | Physical Form: Powder | Texture: Other | Variety: Nutrition Feeds | Delivery Time: 1 Day | Supply Ability: 1 Per Day",
      price: "450 INR/Pack",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    }
    ,{
      id: "productdetails-24",
      name: "Cattle Feed Supplements",
      image: product3,
      description: "Price: 450 INR/Pack | Supply Ability: 1 Per Day | Delivery Time: 1 Days | Variety: Nutrition Feeds | Texture: Other | Physical Form: Powder",
      price: "450 INR/Pack",
          relatedDetails: [
  { id: "productdetails-1", name: "Cattle", image: product1 },
  { id: "productdetails-2", name: "Goat", image: product2 },
  { id: "productdetails-3", name: "Sheep", image: product1 },
  { id: "productdetails-4", name: "Horse", image: product2 },
  { id: "productdetails-5", name: "Poultry", image: product1 },
  { id: "productdetails-6", name: "Pig", image: product2 },
  { id: "productdetails-7", name: "Buffalo", image: product1 },
  { id: "productdetails-8", name: "Rabbit", image: product2 },
  { id: "productdetails-9", name: "Camel", image: product1 },
  { id: "productdetails-10", name: "Duck", image: product2 },
  { id: "productdetails-11", name: "Lamb", image: product1 },
  { id: "productdetails-12", name: "Alpaca", image: product2 },
  { id: "productdetails-13", name: "Donkey", image: product1 },
  { id: "productdetails-14", name: "Turkey", image: product2 },
  { id: "productdetails-15", name: "Quail", image: product1 },
  { id: "productdetails-16", name: "Fowl", image: product2 },
  { id: "productdetails-17", name: "Bison", image: product1 },
  { id: "productdetails-18", name: "Goose", image: product2 },
  { id: "productdetails-19", name: "Zebra", image: product1 },
  { id: "productdetails-20", name: "Llama", image: product2 },
  { id: "productdetails-21", name: "Pony", image: product1 },
  { id: "productdetails-22", name: "Ox", image: product2 },
  { id: "productdetails-23", name: "Cow", image: product1 },
  { id: "productdetails-24", name: "Peacock", image: product2 }
      ],
    }
    ,
    
  ]);

  const handleCardClick = (productdetails) => {
    navigate(`/product-description/${productdetails.id}`, { state: { productdetails, productdetailsList } });
  };

  return (
    <div className="product-details-livestock-container">
      <h1>Livestock Products</h1>
      <div className="product-details-grid">
        {productdetailsList.map((productdetails) => (
          <ProductCard
            key={productdetails.id}
            productdetails={productdetails}
            onCardClick={() => handleCardClick(productdetails)}
          />
        ))}
      </div>



    </div>
  );
};

export default Livestock;
